### ISSUE TITLE
9 Compatibility problems

### ISSUE THREAD

**Issue by stephanj** [devoxx/DevoxxGenieIDEAPlugin#1]
![image](https://github.com/devoxx/DevoxxGenieIDEAPlugin/assets/179457/289a9eb7-84bd-4046-a73e-e36271949a48)

## Package 'android.net' is not found
Package 'android.net' is not found (1 problem)
Package 'android.net' is not found along with its 2 classes.
Probably the package 'android.net' belongs to a library or dependency that is not resolved by the checker.
It is also possible, however, that this package was actually removed from a dependency causing the detected problems. Access to unresolved classes at runtime may lead to NoSuchClassError.
The following classes of 'android.net' are not resolved:
Class X509TrustManagerExtensions is referenced in
AndroidCertificateChainCleaner.<init>(...)
AndroidCertificateChainCleaner.clean(List, String)
AndroidCertificateChainCleaner.Companion.buildIfSupported(...)
AndroidCertificateChainCleaner.x509TrustManagerExtensions
Class SSLSockets is referenced in
Android10SocketAdapter.configureTlsExtensions(...)
Android10SocketAdapter.matchesSocket(SSLSocket)

## Package 'android.os' is not found along with its 3 classes.
Probably the package 'android.os' belongs to a library or dependency that is not resolved by the checker.
It is also possible, however, that this package was actually removed from a dependency causing the detected problems. Access to unresolved classes at runtime may lead to NoSuchClassError.
The following classes of 'android.os' are not resolved:
Class Build.VERSION is referenced in
Android10Platform.<clinit>()
AndroidPlatform.<clinit>()
AndroidPlatform.connectSocket(...)
AndroidPlatform.isCleartextTrafficPermitted(...)
Android10SocketAdapter.Companion.isSupported()
Platform.Android.<init>()
Platform.Android.invokeDefaultMethod(...)
Class Handler is referenced in
Platform.Android.MainThreadExecutor.<init>()
Platform.Android.MainThreadExecutor.execute(...)
Platform.Android.MainThreadExecutor.handler
Class Looper is referenced in
Platform.Android.MainThreadExecutor.<init>()

## Package 'android.security' is not found 
Package 'android.security' is not found along with its class NetworkSecurityPolicy.
Probably the package 'android.security' belongs to a library or dependency that is not resolved by the checker.
It is also possible, however, that this package was actually removed from a dependency causing the detected problems. Access to unresolved classes at runtime may lead to NoSuchClassError.
The following classes of 'android.security' are not resolved:
Class NetworkSecurityPolicy is referenced in
Android10Platform.isCleartextTrafficPermitted(...)
AndroidPlatform.isCleartextTrafficPermitted(...)

## Package 'android.util' is not found 
Package 'android.util' is not found along with its class Log.
Probably the package 'android.util' belongs to a library or dependency that is not resolved by the checker.
It is also possible, however, that this package was actually removed from a dependency causing the detected problems. Access to unresolved classes at runtime may lead to NoSuchClassError.
The following classes of 'android.util' are not resolved:
Class Log is referenced in
AndroidLog.androidLog$okhttp(...)
AndroidLog.enableLogging(String, String)

## Package 'org.bouncycastle.jsse' is not found
Package 'org.bouncycastle.jsse' is not found along with its 3 classes.
Probably the package 'org.bouncycastle.jsse' belongs to a library or dependency that is not resolved by the checker.
It is also possible, however, that this package was actually removed from a dependency causing the detected problems. Access to unresolved classes at runtime may lead to NoSuchClassError.
The following classes of 'org.bouncycastle.jsse' are not resolved:
Class BCSSLSocket is referenced in
BouncyCastlePlatform.configureTlsExtensions(...)
BouncyCastlePlatform.getSelectedProtocol(...)
BouncyCastleSocketAdapter.configureTlsExtensions(...)
BouncyCastleSocketAdapter.getSelectedProtocol(...)
BouncyCastleSocketAdapter.matchesSocket(SSLSocket)
BouncyCastleSocketAdapter.Companion.factory$1.matchesSocket(...)
Class BCSSLParameters is referenced in
BouncyCastlePlatform.configureTlsExtensions(...)
BouncyCastleSocketAdapter.configureTlsExtensions(...)
Class BouncyCastleJsseProvider is referenced in
BouncyCastlePlatform.<init>()

## Package 'org.conscrypt' is not found
Package 'org.conscrypt' is not found along with its 3 classes.
Probably the package 'org.conscrypt' belongs to a library or dependency that is not resolved by the checker.
It is also possible, however, that this package was actually removed from a dependency causing the detected problems. Access to unresolved classes at runtime may lead to NoSuchClassError.
The following classes of 'org.conscrypt' are not resolved:
Class Conscrypt is referenced in
ConscryptPlatform.<clinit>()
ConscryptPlatform.<init>()
ConscryptPlatform.Companion.atLeastVersion(...)
ConscryptSocketAdapter.configureTlsExtensions(...)
ConscryptSocketAdapter.Companion.factory$1.matchesSocket(...)
...and 5 other places...
Class ConscryptHostnameVerifier is referenced in
ConscryptPlatform.DisabledHostnameVerifier
ConscryptPlatform.platformTrustManager()
Class Conscrypt.Version is referenced in
ConscryptPlatform.Companion.atLeastVersion(...)

## Package 'org.openjsse' is not found 
Package 'org.openjsse' is not found along with its 3 classes.
Probably the package 'org.openjsse' belongs to a library or dependency that is not resolved by the checker.
It is also possible, however, that this package was actually removed from a dependency causing the detected problems. Access to unresolved classes at runtime may lead to NoSuchClassError.
The following classes of 'org.openjsse' are not resolved:
Class SSLSocket is referenced in
OpenJSSEPlatform.configureTlsExtensions(...)
OpenJSSEPlatform.getSelectedProtocol(SSLSocket)
Class SSLParameters is referenced in
OpenJSSEPlatform.configureTlsExtensions(...)
Class OpenJSSE is referenced in
OpenJSSEPlatform.<init>()

## Package 'org.osgi' is not found 
Package 'org.osgi' is not found along with its 6 classes.
Probably the package 'org.osgi' belongs to a library or dependency that is not resolved by the checker.
It is also possible, however, that this package was actually removed from a dependency causing the detected problems. Access to unresolved classes at runtime may lead to NoSuchClassError.
The following classes of 'org.osgi' are not resolved:
Class BundleContext is referenced in
OSGiExtensionLoader.context
OSGiExtensionLoader.start(BundleContext)
OSGiExtensionLoader.stop(BundleContext)
Class BundleActivator is referenced in
OSGiExtensionLoader
Class Filter is referenced in
OSGiExtensionLoader.getExtension(Class, String)
Class FrameworkUtil is referenced in
OSGiExtensionLoader.getExtension(Class, String)
Class InvalidSyntaxException is referenced in
OSGiExtensionLoader.getExtension(Class, String)
Class ServiceTracker is referenced in
OSGiExtensionLoader.getExtension(Class, String)

## Abstract method TypeVariable.getAnnotatedBounds() is not implemented (1 problem)
Concrete class TypeVariableImpl inherits from TypeVariable but doesn't implement the abstract method getAnnotatedBounds(). This can lead to AbstractMethodError exception at runtime.

**Comment by deniswsrosa** [comment]
I tried to run the project with the version that was throwing the errors above, and everything was fine:
![Screenshot 2024-04-15 at 10 16 17](https://github.com/devoxx/DevoxxGenieIDEAPlugin/assets/216006/1e0850a9-32f3-4beb-9281-b934e51eb967)
![Screenshot 2024-04-15 at 10 16 37](https://github.com/devoxx/DevoxxGenieIDEAPlugin/assets/216006/c0b406ec-d24b-44ee-800f-5569589729ad)

The plugin verifier task also doesn't throw any errors: 
![Screenshot 2024-04-15 at 10 17 34](https://github.com/devoxx/DevoxxGenieIDEAPlugin/assets/216006/0ed11328-207b-4f49-b549-28f884cd8c00)
![Screenshot 2024-04-15 at 10 18 12](https://github.com/devoxx/DevoxxGenieIDEAPlugin/assets/216006/672f2b35-8034-4b87-b08d-a081a46abbd1)

**Comment by stephanj** [comment]
Same here, so not sure why the IDEA marketplace is informing me about these...
![image](https://github.com/devoxx/DevoxxGenieIDEAPlugin/assets/179457/e75eb252-7876-4b7f-9410-a60393170015)

**Comment by hsz** [comment]
Hey, Stephan!

Looking at the Gradle configuration, I need to highlight a few problems:

- You use `2023.3.4` as a target platform, but there's `sinceBuild` set to `222`, which indicates `2022.2.*`. This is way too low.
  Please set `sinceBuild` to `233` (as the platform is `20*23.3*.4`)
- There's no valid reason to use the `shadowJar`. Gradle IntelliJ Plugin prepares a ZIP archive when running the `buildPlugin` task. You'll find it in the `build/distributions/` directory
- It is recommended to use the `publishPlugin` task for releasing the plugin
- You use Java 19+ to develop the plugin. Since `2022.3`, the IntelliJ Platform relies on Java 17 for running. Having no `shadowJar` involved and an issue related to the Records you use was spotted by Plugin Verifier:
  ![image](https://github.com/devoxx/DevoxxGenieIDEAPlugin/assets/108333/da770d27-04eb-4606-8919-b5b537374c8f)

I believe that will make sense to you. Let me know if you need any further assistance with that. I'm happy to help!

**Comment by stephanj** [comment]
Looking good! 

![image](https://github.com/devoxx/DevoxxGenieIDEAPlugin/assets/179457/3d6b35ac-9378-4948-86a5-c586092666c4)
