### ISSUE TITLE
user ollama, but Timeout occurred.

### ISSUE THREAD

**Issue by wadeKings** [devoxx/DevoxxGenieIDEAPlugin#169]
ollama run deepseek-coder-v2:16b, but devoxxGenie Timeout occurred. Please increase the timeout settings , i am settings timeout 10s
![image](https://github.com/user-attachments/assets/ea553088-012f-4ac0-93b7-a0fb07eb85ea)
![image](https://github.com/user-attachments/assets/4a749866-69cf-4f79-ab81-18273b250428)
![image](https://github.com/user-attachments/assets/de664b25-756e-4dfe-86e1-aaf671c99303)

**Comment by wadeKings** [comment]
supplement： idea version is 2024.1

**Comment by stephanj** [comment]
You should increase the timeout of DevoxxGenie for example to 120s because Ollama needs more time to handle your request.

![image](https://github.com/user-attachments/assets/20c22a23-3a8f-4f97-83e9-97f970d06242)
