### ISSUE TITLE
Does Copy Project / Excluded Directories work?

### ISSUE THREAD

**Issue by dmcg** [devoxx/DevoxxGenieIDEAPlugin#230]
Thanks for the cool tool, but ... ;-)

I have a [project](https://github.com/dmcg/gilded-rose-tdd) with a large json file in src/test/resources.

If I add the full project to the prompt context - Added. Project context 167K tokens
If I delete the directory and add the full project to the prompt context - Added. Project context 44K tokens
If I add src/test/resources to the excluded directories - Added. Project context 167K tokens

Even specifying the exact subdir containing the .json file doesn't seem to help

**Comment by stephanj** [comment]
The current implementation only supports one directory names. 
So if you want to ignore the "resources" directory you should only add "resources" and not "src/test/resources".   Can you give it a try and let me know?

**Comment by dmcg** [comment]
Aha - that doesn the trick, and I hadn't found the add directory, so thanks.

On reflection ignore particular files is probably what I want, or maybe parsing a .gitignore like thing. That would let me have per-project settings.
