### ISSUE TITLE
Support deepseek.com as LLM provider

### ISSUE THREAD

**Issue by dmurat** [devoxx/DevoxxGenieIDEAPlugin#261]
Besides being able to run the 7b deepseek-coder-v2 model through Ollama, it would be helpful to add support for 
www.deepseek.com to enable access to the large deepseek-coder-v2 model.

It looks like the deepseek-coder-v2 large model is very close to the sonnet 3.5:
https://bigcode-bench.github.io/
https://huggingface.co/spaces/bigcode/bigcodebench-leaderboard
https://aider.chat/docs/leaderboards/

Cheers

**Comment by stephanj** [comment]
The DeepSeek API uses an API format compatible with OpenAI. 
https://platform.deepseek.com/api-docs

**Comment by dmurat** [comment]
Wow. 🚀 
Thank you.

**Comment by stephanj** [comment]
I did not purchase any credits, so can you test it for us 😜

**Comment by dmurat** [comment]
Sure thing 😄
Is it released already? 😮

**Comment by stephanj** [comment]
Should be available on the Marketplace tomorrow afternoon OR you can install it manually from
https://github.com/devoxx/DevoxxGenieIDEAPlugin/releases/tag/v0.2.16

**Comment by dmurat** [comment]
I will wait for the Marketplace and will report back.

**Comment by stephanj** [comment]
That was also fast, now available on the JetBrains marketplace
https://plugins.jetbrains.com/plugin/24169-devoxxgenie/versions

**Comment by dmurat** [comment]
This is great 😄 

I tried the model, and everything worked nicely. I quickly compared the output with that of Sonnet 3.5, and it looks very impressive. The use case was adding a new test method to the complex Groovy/Spock/SpringBoot integration test.

Considering that deepseek costs almost 40 times less than Sonnet, it is a great option to have it. Also, as far as I understand, Deepseek has context caching enabled by default for all users, which should reduce the cost even further.

Anyway, thank you very much for adding this support. 🥳 🚀

**Comment by stephanj** [comment]
Did you try both streaming response and non streaming?

**Comment by stephanj** [comment]
Also make sure to set the temperature to 0 when using it for coding (in the plugin LLM Settings page)
<img width="415" alt="image" src="https://github.com/user-attachments/assets/1ddff283-f178-4018-9eae-1a4a6ba6d0b6">
