### ISSUE TITLE
Enhancement: Diff mode

### ISSUE THREAD

**Issue by daviddenton** [devoxx/DevoxxGenieIDEAPlugin#304]
I'm imagining a mode in the plugin where you can configure the model to just reply in diffs. On completion of a prompt, the diff is automatically opened up using the intellij diff editor (I think it's DiffManager?) where you can then accept it straight into the project. The diff would remain in the chat window so you could make further tweaks to the request.

I think this should be able to be done with the APIs.... But would be absolutely amazing as a workflow (and maybe having read the Instant apply stuff easier?)

Keep up the good work!

**Comment by stephanj** [comment]
Couldn't you ask in the prompt for a path file, see demo below.
Example @ https://youtu.be/Rs8S4rMTR9s?feature=shared&t=1294

**Comment by daviddenton** [comment]
Yes - you can do this - the video in question was actually the reason behind this idea 😄 . But it just seemed so incredibly manual when the tools are there in the Idea API to make it better. 🤷
