### ISSUE TITLE
[Bug] GPT4All doesn't show any model

### ISSUE THREAD

**Issue by Heezer** [devoxx/DevoxxGenieIDEAPlugin#307]
I believe it was working, looks like it's broken now 😭 
Plugin version: 0.2.22
GPT4All API server is running, I'm getting my models under http://localhost:4891/v1/models

Looking forward to find the time and join your great project! and probably reproduce and fix the issue on my own 😄

**Comment by stephanj** [comment]
We never listed the models from GPT4ALL only for LMStudio and Ollama.
Put if a REST request exists then please share so we can make this happen.

**Comment by Heezer** [comment]
Ahh, ok, my bad. The thing is GPT4All fails with:
```
java.lang.IllegalArgumentException: No factory for provider: GPT4All
	at com.devoxx.genie.chatmodel.ChatModelProvider.lambda$getFactory$0(ChatModelProvider.java:49)
	...
```

**Comment by stephanj** [comment]
Will have a closer look once Devoxx Belgium is behind us 😅
