### ISSUE TITLE
'Copy directory to clipboard' does not include file contents for TypeScript or SCSS files

### ISSUE THREAD

**Issue by wimdeblauwe** [devoxx/DevoxxGenieIDEAPlugin#308]
I have a project that uses Web Components. It has TypeScript and SCSS files in it. When I select 'Copy directory to clipboard', it does not not add the file contents of the files. When I try this on a Java project, the Java code is included.

**Comment by stephanj** [comment]
You just need to edit the "Scan & Copy Projects" settings, and include the .ts and .scss files
![image](https://github.com/user-attachments/assets/fbafb1fa-13d3-4896-97a1-e54b7adf839d)

**Comment by mydeveloperplanet** [comment]
It makes sense to add frontend file extensions to the default file extensions. I know that some of my colleagues will just say 'it does not work' instead of raising an issue. Created a PR for this.
