### ISSUE TITLE
[Feature] Support for Azure OpenAI Provider

### ISSUE THREAD

**Issue by tanerilyazov** [devoxx/DevoxxGenieIDEAPlugin#315]
### Azure OpenAI Support
Azure OpenAI Service provides access to OpenAI's models including the GPT-4o, GPT-4o mini, GPT-4, GPT-4 Turbo with Vision, GPT-3.5-Turbo, DALLE-3 and Embeddings model series with the security and enterprise capabilities of Azure.

The API is uses a specific endpoint, which depends on Azure resource names, specific way of passing the API key, `api-key: {API_KEY}` header instance of `Authorization` header with Bearer token...

`https://{AZURE_OPENAI_SERVICE_RESOURCE}.openai.azure.com/openai/deployments/{DEPLOYMENT_NAME}/chat/completions?api-version={API_VERSION}`

So the way we call it is a bit more specific and we also need to pass in a few more parameters, so it's probably nice to have the options for Azure OpenAI not always visible.

A lot of enterprises will provide Azure credits to teams, so there may be people who are going to want to use OpenAI models from Azure, rather than calling the OpenAI APIs directly.

**Comment by tanerilyazov** [comment]
I'm not sure how relevant this is to #156

**Comment by mydeveloperplanet** [comment]
In release v0.24.0
