### ISSUE TITLE
Exception on IntelliJ IDEA launch and settings not saved

### ISSUE THREAD

**Issue by clubshrimp** [devoxx/DevoxxGenieIDEAPlugin#319]
I'm experiencing an issue with the DevoxxGenieIDEAPlugin in IntelliJ IDEA. The plugin is causing an exception when launching the IDE, and the settings are not being saved between restarts.

## Problem Description

1. When launching IntelliJ IDEA, an exception occurs related to the DevoxxGenieIDEAPlugin.
2. I can access and modify the settings, but upon restarting IntelliJ IDEA, the changes are not preserved.

## Environment Details

- IntelliJ IDEA version: IntelliJ IDEA 2024.2.3 (Ultimate Edition)
- Operating System: Pop!_OS 22.04 LTS
- DevoxxGenieIDEAPlugin version: 0.2.22

## Steps to Reproduce

1. Launch IntelliJ IDEA with the DevoxxGenieIDEAPlugin installed.
2. Observe the exception occurring during startup.
3. Navigate to the plugin settings and make changes.
4. Restart IntelliJ IDEA.
5. Verify that the changes made to the settings are not saved.

## Expected Behavior

- IntelliJ IDEA should launch without exceptions related to the DevoxxGenieIDEAPlugin.
- Any changes made to the plugin settings should be preserved between IDE restarts.

## Actual Behavior

- An exception occurs during IntelliJ IDEA startup.
- Settings changes are not saved after restarting the IDE.

## Exception Details

The exception encountered is a `CycleInitializationException` related to `com.devoxx.genie.ui.settings.DevoxxGenieStateService`. The full stack trace is provided in the attached file.

## Attachments

1. [About intellij.txt](https://github.com/user-attachments/files/17474213/About.intellij.txt) - Contains additional details about the IntelliJ IDEA installation.
2. [CycleInitializationException_DevoxxGenieStateService.txt](https://github.com/user-attachments/files/17474237/CycleInitializationException_DevoxxGenieStateService.txt) - Full exception stack trace.

I appreciate any assistance in finding a solution to this issue. Thank you !

**Comment by mydeveloperplanet** [comment]
It looks like your settings are corrupted. Can you check the file in your home directory: ~/.config/JetBrains/IdeaIC2024.2/options/DevoxxGenieSettingsPlugin.xml ?
You could try removing it (you will lose your settings though, so maybe backup it) and try again?

**Comment by mydeveloperplanet** [comment]
Looks like issue #293 , not entirely the same, but similar

**Comment by clubshrimp** [comment]
Thank you for your quick response and helpful suggestion. You're absolutely right - the issue seems to be related to corrupted settings. I checked the file you mentioned, and here's what I found: 

````
<application>
  <component name="com.devoxx.genie.ui.SettingsState">
    <option name="customPrompts">
      <list>
        <CustomPrompt>
          <option name="name" value="test" />
          <option name="prompt" value="Write a unit test for this code using JUnit." />
        </CustomPrompt>
        <CustomPrompt>
          <option name="name" value="explain" />
          <option name="prompt" value="Break down the code in simple terms to help a junior developer grasp its functionality." />
        </CustomPrompt>
        <CustomPrompt>
          <option name="name" value="review" />
          <option name="prompt" value="Review the selected code, can it be improved or are there any bugs?" />
        </CustomPrompt>
      </list>
    </option>
  </component>
</application>
````

I removed the original file and restarted IntelliJ IDEA.

After removing the file and restarting:

- The exception no longer occurs during startup.
- I was able to access and modify the plugin settings.
- Upon subsequent restarts, the settings are now being saved correctly.

The new settings file has the same permissions as the old ones
.rw-rw-r--  787 myusername 10 Oct 10:00 DevoxxGenieSettingsPlugin.xml
.rw-rw-r-- 6.7k myusername 22 Oct 17:42 DevoxxGenieSettingsPlugin.xml

But contains a lot more data

This solution appears to have resolved both the startup exception and the issue with settings not being saved.

Thank you for pointing out the similarity to issue #293.  I am sorry I missed it previously, I was only looking at open issues ! I should haved looked at those closed as well.

**Comment by mydeveloperplanet** [comment]
Wel thank your for the elaborate reporting. If this occurs more often, we need to investigate it further.
