### ISSUE TITLE
[Refactoring] Replace invocations of SwingUtilities.invokeLater()

### ISSUE THREAD

**Issue by mydeveloperplanet** [devoxx/DevoxxGenieIDEAPlugin#324]
According to https://plugins.jetbrains.com/docs/intellij/threading-model.html#invoking-operations-on-edt-and-modality SwingUtilities.invokeLater() should not be used.
Use `ApplicationManager.getApplication().invokeLater()` instead.

**Comment by stephanj** [comment]
I've included this refactoring in my last push... couldn't resist it :)

**Comment by stephanj** [comment]
Agreed, but looks promising.
