### ISSUE TITLE
Exclude a single file?

### ISSUE THREAD

**Issue by dennysfredericci** [devoxx/DevoxxGenieIDEAPlugin#325]
Is there a way to exclude a specific file?

I have an Angular project, and I'd like to omit the `package-lock.json` file from the prompt. It’s unnecessarily large, with 14,627 lines in this relatively small project.

**Comment by dennysfredericci** [comment]
Yep, looks like only directories can be excluded or files via .gitignore

**Comment by mydeveloperplanet** [comment]
You can also remove the json extension from the to be included file extensions but this is a suboptimal solution. Maybe we should also allow to exclude specific files besides the .gitignore file. 
The package.json needs to be committed, but we do not want it to send to an LLM.
In my current project:
* including json extension: 1M tokens
* excluding json extension: 217K tokens

**Comment by stephanj** [comment]
Agreed, excluding specific files is a must-have.  Will add it to my to-do list for this month :)

**Comment by stephanj** [comment]
Couldn't resist and used DevoxxGenie and Claude Sonnet 3.5 (new) to suggest how to implement the feature.  The suggested code look great and just worked. #MetaProgramming 

![image](https://github.com/user-attachments/assets/b3e1e35d-1533-4ee9-b20f-43929380af37)

Details @ https://github.com/devoxx/DevoxxGenieIDEAPlugin/pull/326

**Comment by dennysfredericci** [comment]
Hey! Now I have way fewer tokens since package-lock.json is excluded. Thanks, @stephanj!  🚀

Also, I updated IntelliJ to version 2023.2.2 and changed sinceBuild to 232 to install the plugin on slightly older IntelliJ versions. I am testing it now. If everything works, can I open a PR?

**Comment by stephanj** [comment]
If everything still works, then a PR is very welcome.  Thanks!
