### ISSUE TITLE
Error: top_p must be 1 when using greedy sampling with Cloud Mistral models

### ISSUE THREAD

**Issue by clubshrimp** [devoxx/DevoxxGenieIDEAPlugin#338]
## Description
When using Devoxx Genie with a Cloud Mistral model (using api key) in IntelliJ IDEA, receiving error:

```
CompletionException - com.devoxx.genie.service.exception.ProviderUnavailableException:
java.lang.RuntimeException: status code: 400; body: {
"object": "error",
"message": "top_p must be 1 when using greedy sampling.",
"type": "invalid_request_error",
"param": null,
"code": null
}
```

## Environment
- IntelliJ IDEA version: IntelliJ IDEA 2024.3 (Ultimate Edition)
Build #IU-243.21565.193, built on November 13, 2024
Runtime version: 21.0.5+8-b631.16 amd64 (JCEF 122.1.9)
- Devoxx Genie version: V0.2.27
- Operating System: Fedora Linux 41 (Workstation Edition)
- Model: Mistral Codestral, Mistral Large

## Expected Behavior
Plugin should handle Mistral model requests without errors.

## Actual Behavior
Request fails and intellij idea shows the error above

Thank you for this great plugin !

**Comment by clubshrimp** [comment]
I apologize for the confusion. This issue was due to a misconfiguration on my end. The error message was actually quite clear:

"top_p must be 1 when using greedy sampling."

I wasn't aware of the top_p parameter in the settings, and since it was working fine with another Cloud LLM providers, I didn't consider it could be an issue on my side. After adjusting the configuration, the problem has been resolved.

This isn't a bug in the plugin or the Mistral API, but rather a user error. I'm closing this issue as it doesn't require any changes to the codebase. Thank you for your attention, and I apologize for any inconvenience caused.

**Comment by mydeveloperplanet** [comment]
No problem, good to read that you could resolve it yourself and thanks for the feedback :+1:
