### ISSUE TITLE
o1-preview not working due to system prompt

### ISSUE THREAD

**Issue by sakariye** [devoxx/DevoxxGenieIDEAPlugin#340]
OpenAI's o1-preview model does not support system prompts. As result if you select it from the drop-down and send a message, it gives the following error:

`An unexpected error occurred: OpenAiHttpException - { "error": { "message": "Unsupported value: 'messages[0].role' does not support 'system' with this model.", "type": "invalid_request_error", "param": "messages[0].role", "code": "unsupported_value" } } Please check the IDE log for more details.
`

There is no way to disable the system prompt either. I tried removing the content of the system prompt box but that didn't fix it. Would be nice to be able to disable system prompt.

**Comment by stephanj** [comment]
I just tried it and it does work, can you check if you have the latest version of plugin : v0.2.27  
You can see the version in the settings footer.

![image](https://github.com/user-attachments/assets/2a44108f-698a-478a-ac4b-8a9f979d5689)

![image](https://github.com/user-attachments/assets/53a58eea-46b8-4928-a9a4-0c71201920a8)

**Comment by sakariye** [comment]
Not an issue.
