### ISSUE TITLE
[question] What is the gap between github release and availability on jetbrains marketplace?

### ISSUE THREAD

**Issue by Slach** [devoxx/DevoxxGenieIDEAPlugin#342]
I still see old version 0.2.27 on https://plugins.jetbrains.com/plugin/24169-devoxxgenie/versions

**Comment by stephanj** [comment]
We first release on GitHub so we can have some extra people test the new release.
Only after a couple of days we push it to the Jetbrains marketplace where it takes minimum two days to get reviewed and. approved.  Only then is it available on the marketplace.
