### ISSUE TITLE
Select the code and ask for Javadoc/Comments

### ISSUE THREAD

**Issue by dmitrijszaharovs** [devoxx/DevoxxGenieIDEAPlugin#363]
**Windows 10;
Intellij IDEA 2024.3
DevoxxGenie: v. 0.4.1
LLM: Cloud LLM - OpenAI only**

I'm working with Python and Terraform.
How can I (after adding the whole project to the prompt context, or without it - tried both ways), say, ask DevoxxGenie to generate Javadoc or comments **for the code, which I've selected in an editor window**?

My custom prompt:
```
/tfdoc: Create short documentation in a Javadoc style (use "#" as comments, add meaningful title, add brief explanation - why it is needed, exclude parameters, characteristics, and usage, only summary) for selected Terraform code
```
But I can only get something like a global project description.

I'm developing a Terraform module for database backup/restore operations.
In my editor window I'm selecting a code:
```
resource "azurerm_mssql_firewall_rule" "devMonitorDashboard1" {
  name             = "Admin"
  server_id        = azurerm_mssql_server.devsqlserver.id
  start_ip_address = var.ADMIN_IP_ADDRESS
  end_ip_address   = var.ADMIN_IP_ADDRESS
}
```
then, call DevoxxGenie, type `/tfdoc` and get the response:
```
# Terraform Database Backup and Restore Module 
# 
# This module facilitates the automation of database backup and restore processes in a cloud environment. 
# It is crucial for maintaining data integrity, ensuring business continuity, and enabling quick recovery 
# from data loss scenarios. By using this module, organizations can implement reliable backup strategies 
# and streamline their disaster recovery plans. 
```
How can I generate a description for this my selected code?

**Comment by stephanj** [comment]
I've tried with Anthropic Claude Sonnet 3.5 and this is what I get using your /tfdoc prompt.  

You can select a piece of "code" which is what will be used in the prompt, or just open the editor and the default open file will be used.  You don't have to add the full project if you only are working on one file.

BTW You should also try to set the System Prompt and see if that helps.

<img width="1613" alt="Screenshot 2024-12-11 at 09 13 30" src="https://github.com/user-attachments/assets/e10a6d06-2d20-4c7b-8c08-847e2efdf4a2">

<img width="1230" alt="image" src="https://github.com/user-attachments/assets/9dba3952-7c4b-4b94-b947-817d2a3780af">
