### ISSUE TITLE
Missing characters when used with LM Studio

### ISSUE THREAD

**Issue by piotrkosecki** [devoxx/DevoxxGenieIDEAPlugin#37]
I've asked a LLM in LM Studio to generate Scala Slick classes for given db table - from log in LM Studio it looks fine:
<img width="1236" alt="Screenshot 2024-04-29 at 09 49 19" src="https://github.com/devoxx/DevoxxGenieIDEAPlugin/assets/2283610/dd4c9703-cac1-4218-b3ad-379d261f94c9">
But in DevoxxGenie it misses some characters:
<img width="561" alt="Screenshot 2024-04-29 at 09 49 25" src="https://github.com/devoxx/DevoxxGenieIDEAPlugin/assets/2283610/32245ca5-c247-4270-8f1d-6e3609af4f36">

**Comment by stephanj** [comment]
Can you confirm that you have version 0.0.14 installed?

**Comment by piotrkosecki** [comment]
I can confirm that it still sometimes happen in the 0.1.2
<img width="569" alt="Screenshot 2024-05-07 at 09 29 06" src="https://github.com/devoxx/DevoxxGenieIDEAPlugin/assets/2283610/59fc3212-7523-42eb-8a08-82e75683ac94">

**Comment by stephanj** [comment]
Which model are you using with LMStudio, so I can simulate it.  #Thanks

**Comment by piotrkosecki** [comment]
yes, but sometimes for the same question and model it responds correctly, sometimes it breaks, I'll try to reproduce and paste here with logs for each case

**Comment by piotrkosecki** [comment]
I think I know what the problem is. Sometimes model does not put the response in the markdown:
<img width="1219" alt="Screenshot 2024-05-07 at 12 15 03" src="https://github.com/devoxx/DevoxxGenieIDEAPlugin/assets/2283610/06a87645-1f73-43b8-aaeb-0d7af344b153">
<img width="561" alt="Screenshot 2024-05-07 at 12 16 17" src="https://github.com/devoxx/DevoxxGenieIDEAPlugin/assets/2283610/0979b8ee-828e-4a8b-b5a7-9865884e4d3f">

**Comment by piotrkosecki** [comment]
after regeneration it returns with ``` and it looks ok:
<img width="578" alt="Screenshot 2024-05-07 at 12 17 37" src="https://github.com/devoxx/DevoxxGenieIDEAPlugin/assets/2283610/7f0aef1f-7c34-49fa-8538-318b56dc7067">
<img width="1258" alt="Screenshot 2024-05-07 at 12 18 21" src="https://github.com/devoxx/DevoxxGenieIDEAPlugin/assets/2283610/529cbe38-473e-4393-9c7d-76184b685ab2">

**Comment by stephanj** [comment]
This is the challenge/down side of supporting many different local & cloud based chat models.  
They all come with there own (little) quirks.
