### ISSUE TITLE
[FEATURE REQUEST] : As a software engineer working in a really secured company regarding cloud based llm usages, i need a way to enable/disable Providers so i can restrict only those authorized by my company

### ISSUE THREAD

**Issue by samkerr4coding** [devoxx/DevoxxGenieIDEAPlugin#373]
I'm currently working for a company that implements relatively high standard of security especially about cloud remote AI/LLM.
I would like to promote this nice plugin as an alternative to copilot in my current company, consequently i think it could be a good feature to have the ability to enable/disable llm providers (even some locals). Ideally my configuration would be to keep only Ollama for local and Azure Open AI (and disable all the others)

Is it possible ?

**Comment by stephanj** [comment]
You can enable/disable LLM Providers since version 0.4.1
https://github.com/devoxx/DevoxxGenieIDEAPlugin/releases/tag/v0.4.1 

<img width="805" alt="image" src="https://github.com/user-attachments/assets/fd9fa2ce-e6d5-449e-a543-e9d8fb200050" />
