### ISSUE TITLE
Chat memory is not cleared when opening new project

### ISSUE THREAD

**Issue by mydeveloperplanet** [devoxx/DevoxxGenieIDEAPlugin#413]
DevoxxGenie 0.4.6

The chat memory is not cleared when switching to a new project.

Reproducible as follows:
1. Add a file to the prompt context
2. ask a question 'tell me something about this file'
3. The response explains the file
4. open a new project (in a new IntelliJ window)
5. ask a question 'tell me something about this file'
6. The response is about the file added in step 1 (from another project)

With LMStudio I could see that the chat memory from the previous project is sent in step 5

A workaround is to open a new chat window. However, the opened selected file is not sent as prompt context. This is maybe related to this issue because when I close all IntelliJ windows and ask this question, the opened selected file is sent as prompt context.

**Comment by stephanj** [comment]
Hey Gunther, please verify related PR from Samir!

**Comment by mydeveloperplanet** [comment]
Issue is fixed, thanks @samkerr4coding !
