### ISSUE TITLE
Settings Changes don't get applied and persisted

### ISSUE THREAD

**Issue by TrautmannP** [devoxx/DevoxxGenieIDEAPlugin#5]
Foremost: Great Plugin, and thanks for developing it!

**Issue:** 
Changes inside the DevoxxGenie Settings Modal don't get applied and persisted

**Reproduction:**
1. Open Settings → Devoxx Genie Settings
2. Change Ollama URL to something else.
3. Click “OK”.

**Description:**
I'm using a self-hosted Ollama Instance on my Interference Server. When I tried to change the Ollama Base URL, I noticed that changes don't get applied. After restarting IDEA, I also noticed that changes don't get persisted.

I checked the source code and noticed that there is no usage of IDEA's State Services. I'm by far no experienced IntelliJ Plugin Developer, but I addressed the problem by following the IDEA suggestions. Furthermore, I will create a Pull Request in a few minutes for a review and further tests.

**Comment by stephanj** [comment]
Thanks for the PR!!
