### ISSUE TITLE
Add a cog icon in the DevoxxGenie menu bar

### ISSUE THREAD

**Issue by stephanj** [devoxx/DevoxxGenieIDEAPlugin#7]
Would be nice to have a cog icon/button in the DevoxxGenie menu so the user can go directly to the Settings page.

![image](https://github.com/devoxx/DevoxxGenieIDEAPlugin/assets/179457/5a65a903-8301-41bf-87e8-d89ebf460a00)

**Comment by stephanj** [comment]
Looks like a "Settings" icon is already there, so should be something else that when clicked it takes you to the Settings page.

**Comment by TrautmannP** [comment]
Yeah, you are right. There is a Cog icon if using the "old" IntelliJ UI. It was replaced by three vertical dots in the new UI.

Maybe a Wrench would be an UI independent solution?

![grafik](https://github.com/devoxx/DevoxxGenieIDEAPlugin/assets/42808530/a89d4fc3-bfac-436f-83d3-5b513b7f6aeb)

This Wrench icon is part of the IntelliJ Icon Set and wouldn't need additional resources.
