### ISSUE TITLE
custom prompt box to maximize editing and viewing

### ISSUE THREAD

**Issue by wjlei200** [devoxx/DevoxxGenieIDEAPlugin#88]
Hope to add a custom prompt box to maximize editing and viewing, increase editing and viewing experience, thank you!

<img width="815" alt="image" src="https://github.com/devoxx/DevoxxGenieIDEAPlugin/assets/133096019/c90eba25-ca10-4f79-a789-0c3c2b922a06">

**Comment by stephanj** [comment]
Done

![image](https://github.com/devoxx/DevoxxGenieIDEAPlugin/assets/179457/45d63bad-3b85-4077-8c1c-127db71b8ce4)
