### ISSUE TITLE
No response from LLM #Timeout

### ISSUE THREAD

**Issue by mydeveloperplanet** [devoxx/DevoxxGenieIDEAPlugin#99]
I use IntelliJ IDEA 2024.1.3 (Community Edition) with DevoxxGenie 0.1.15
I have installed Ollama locally

To reproduce:
* I have selected Ollama and 'llama3:latest' in the plugin
* I select a piece of code
* I type /explain in the message prompt
* I click the submit-button
* Nothing happens (and I have waited for a long time)

I uninstalled the plugin, restart IntelliJ, installed the plugin again, restart IntelliJ and tried again, but same issue.

Am I doing something wrong here?

**Comment by stephanj** [comment]
Can you try writing a prompt "Explain this code" instead of using the short code?

**Comment by mydeveloperplanet** [comment]
Same result, I am using Ubuntu 22.04.4 LTS
if there is anything else I can do to help or provide more information, please let me know

**Comment by stephanj** [comment]
You can try a few things:
1) Clone/Fork the project and run the project in IDEA and run/debug in IDE, this way you'll hopefully see what's going on.   
2) Try the "Streaming Response" in the options, this will/should give streaming response but never tried it on Ubunu...  
3) Try to use a Cloud LLM (like OpenAI, or any other one) by adding an API Key in the Options panel, and give this a try.
Keep me posted!

**Comment by mydeveloperplanet** [comment]
I am able to debug the plugin. Now I get a 'Timeout occurred. Please try again.' message. It originates from the `ChatPromptExecutor.runPrompt`

**Comment by stephanj** [comment]
Depending on the model you have chosen (size) and available RAM/GPU/CPU you will need to increase the request time, which you can do in the Settings page.

**Comment by mydeveloperplanet** [comment]
After thorough analysis:
* Used LLMStudio, now I am able to see what is happening on the LLM side (thanks for the tip!)
* Increasing the timout to 240 seconds solves the problem

However, using a timeout of 60 seconds, shows some weird behaviour:
* I start the prompt at 11:49
* At 11:50, the timeout occurs, the 'run' button is enabled again, but the timeout message is not shown. The message is only shown when I click in the DevoxxGenie window.
* But at 11:50:01.187 a new POST request is received. Why?
* At 11:51:02.009 again a new POST request. Why?
* My suggestion: instead of printing the message 'Timeout occurred. Please try again.' it should state 'Timeout occurred. Please increase the timeout setting.'

Another thing:
* although I removed all previous messages, requests from the DevoxxGenie window, it seems that the messages are still send as chat memory to the LLM. This seems not to be correct.

[devoxxgenie-llmstudio-logs.txt](https://github.com/user-attachments/files/15936116/devoxxgenie-llmstudio-logs.txt)

**Comment by stephanj** [comment]
This is the Retry mechanisme kicking in, after the timeout it will try again.
You can set the retry to 0 and then this will only do one POST.

1. But you're right in regards to chat memory, if you remove a chat message these should also be removed from the memory which if not the case is a bug.

2. And the timeout message must be shown automatically without a click in the window.

Thanks for debugging this! 

![image](https://github.com/devoxx/DevoxxGenieIDEAPlugin/assets/179457/ce60d50a-b118-41e3-a952-e8ef46827bf9)

**Comment by mydeveloperplanet** [comment]
Well, thank you for your support! And I learned at least two things:
* LMStudio: this is an awesome local AI :-)
* how to run and debug an IntelliJ plugin

**Comment by stephanj** [comment]
Fixes on there way...

![image](https://github.com/devoxx/DevoxxGenieIDEAPlugin/assets/179457/de1d2767-71d5-4eaf-a188-c220b789a0bc)

**Comment by stephanj** [comment]
Using NotificationUtil so the error/warning is shown immediately to the user.

![image](https://github.com/devoxx/DevoxxGenieIDEAPlugin/assets/179457/35048186-64b4-4127-bccd-9333a2c9a724)

**Comment by stephanj** [comment]
V0.1.18 has been pushed with following fixes:
1) Better error messaging
2) Chat memory is correctly cleaned up when removing messages
When time permits can you pull and test?  #ThanksInAdvance

**Comment by mydeveloperplanet** [comment]
I have tested the changes:
* after the timeout occurs, it is immediately visible ==> check
* The timeout message now contains clear instructions to alter the timeout settings ==> check
* the timeout setting is a JBIntSpinner with minValue=1 and maxValue=60 ==> maxValue should be much larger (yesterday I was able to successfully test with 240, but I noticed today that I changed the value in the code, sorry for that, could have told you this yesterday)
* the maximum retries setting is a JBIntSpinner with minValue=1 and maxValue=5 ==> I cannot set the retry to 0 as you suggested above, but after testing, it seems that minValue=1 ensures that only one attempt is being made. The label `Maximum Retries` is a bit misleading, maybe it is better to label it as `Maximum Attempts`?
* chat memory is correctly cleaned up when removing messages ==> check

Something different: I looked at the PR and noticed that directory core/build was committed. That was by accident, I assume?

**Comment by stephanj** [comment]
Added #109 and #108 

The core/build is part of a bigger refactoring which can be included :)

**Comment by mydeveloperplanet** [comment]
I will try to test it the coming days, but am quite busy.
about core/buid ==> deze are the `.class` files, you are sure you want these in the repository?

**Comment by stephanj** [comment]
Ah damn, will add them to .gitignore  #Thanks

**Comment by mydeveloperplanet** [comment]
Did a final test, LGTM :+1:
